### ISSUE TITLE
Peer-To-Peer Code Review: Capstone Project

### ISSUE THREAD

**Issue by mavericksbalitaan** [IshmaelKargbo/code4easy#2]
## Hi @IshmaelKargbo 😎 

![](https://media.giphy.com/media/3o6fIZjpzcGBzwaayc/giphy.gif

### Here are some of our comments/suggestions: ♻️ 

- [x] We suggest fixing the link to the home in the mobile menu.
- [x] We suggest fixing the alt attributes of the images to make the page more accessible.
- [x] We suggest creating more `button` if preferred. [optional] 
- [x] We suggest changing the `cursor` pointer to the `hand` cursor. [optional]

---
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by IshmaelKargbo** [comment]
Thanks 😊
________________________________
From: Mavericks Balitaan ***@***.***>
Sent: Friday, April 22, 2022 7:09 AM
To: IshmaelKargbo/code4easy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IshmaelKargbo/code4easy] Peer-To-Peer Code Review (Issue #2)


Peer-To-Peer Code Review

[giphy]<https://user-images.githubusercontent.com/98527559/164624472-c655b3c5-90f3-49bf-98e7-2a87d4b068e6.gif>

Nice work on your capstone project!
